name: build_and_test
on:
  - push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: echo building amogus simulation amogus

      - name: Test
        run: echo testing amogus simulation amogus
